### ISSUE TITLE
Remove the R Markdown README.Rmd in the Windows 10 Pro documentation

### ISSUE THREAD

**Issue by znmeb** [hackoregon/data-science-pet-containers#66]
It's not using any R Markdown functionality, unlike the top-level one, which uses R Markdown to get the outline / TOC.

**Comment by nam20485** [comment]
Are you going to take care of this one or would you like me to remove it?

**Comment by znmeb** [comment]
I'll do it - I'm doing another release tonight.

**Comment by znmeb** [comment]
done - closing
