### ISSUE TITLE
AWS S3 integration

### ISSUE THREAD

**Issue by znmeb** [hackoregon/data-science-pet-containers#7]
Like the Cookiecutter data science project does, only simpler without all the scaffolding and Pythonisms and make and something that will run on Windows. ;-)

**Comment by bhgrant8** [comment]
I was hoping we would be able to create a simple shell script around the aws cli client, my hopes is that this would

- [ ] simplify the process that our team uses to distribute data between members

- [ ]  that could run in multiple environments:

* docker container
* cookie cutter
* host system if needed

- [ ] easy to debug

- [ ] follow a process of least permissions necessary on aws buckets

- [ ] allow for some process to decide whether to sync data down from s3 or not

- [ ] use config variables to prevent hardcoding of resource names/secrets

**Comment by znmeb** [comment]
Yeah - after a few hours of dogfooding on Windows in a bandwidth-challenged coffee shop I'm rethinking this. It turns out that the AWS CLI is a Python package; you install it with `pip`. 

I'm designing a "data volume image" that will run in a container and manage raw data. It will look something like the Cookiecutter data science `/data` folder except it will only have read-only "in" and read-write "out" areas. The other containers will be able to mount it and it can be mounted on the host. There are some permissions issues with a writable host mount so I may put an `sftp` server in it ;-)

**Comment by znmeb** [comment]
closing - subsumed by #9
